project:
  type: book

book:
  title: "RStudio Desktop Administration {{< var buildType >}} {{< var version >}}"
  subtitle: "{{< var buildType >}} Version {{< var version >}}"
  page-navigation: true
  site-url: https://docs.rstudio.com/ide/desktop-pro/

  sidebar:
    collapse-level: 1
    style: "docked"
    align: "center"
    background: light

  navbar:
    type: light
    search: true
    pinned: true
    logo: images/RStudio-ball.svg
    right:
      - text: "RStudio.com"
        url: 'https://www.rstudio.com/'
      - text: "Release Notes"
        url: "https://support.rstudio.com/hc/en-us/articles/200716783-RStudio-Release-History"
      - text: "Help"
        url: "https://support.rstudio.com/hc/en-us"

  chapters:
    - part: "Getting Started"
      chapters:
        - text: "Introduction"
          file: index.qmd
        - getting_started/prerequisites.qmd
        - getting_started/installation.qmd
        - getting_started/activation.qmd
    - part: "License Management"
      chapters:
        - text: "Overview"
          file: license_management/license_management.qmd
        - license_management/product_activation.qmd
        - license_management/evaluations.qmd
        - license_management/command_line_operations.qmd
    - part: "Database Drivers"
      chapters:
        - text: "Overview"
          file: database_drivers/database_drivers.qmd
        - database_drivers/install_database_drivers.qmd
    - part: "Settings"
      chapters:
        - text: "Overview"
          file: settings/settings.qmd
        - settings/preferences.qmd
        - settings/other_settings.qmd
    - part: "Remote Desktop"
      chapters:
        - text: "Overview"
          file: remote_desktop/remote_desktop.qmd
        - remote_desktop/session_servers.qmd


  footer:
    pinned: true
    left: |
      Copyright © 2021 RStudio, PBC. All Rights Reserved.
    right:
      - icon: house-fill
        href: https://www.rstudio.com
      - icon: question-circle-fill
        href: https://support.rstudio.com/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.rstudio.com
      - icon: twitter
        href: https://twitter.com/rstudio


number-depth: 2

format:
  html:
    # Controls whether external links open in new windows
    link-external-newwindow: true
    # Controls whether an icon adorns external links (either true or the bootstrap icon name)
    link-external-icon: true
    number-sections: false
    theme:
      - cosmo
      - styles/styles.scss
    include-in-header: google_analytics.html
    toc: true
    code-overflow: scroll
    
  pdf:
    toc: true

  docx:
    toc: true
