---
title: "Preferences"
aliases:
  - /settings.html#preferences
---

## Preferences

User preferences set in the RStudio IDE's *Global Options* dialog can also be set in the JSON file `rstudio-prefs.json`, located in the settings directory described above.

### Example

By default, RStudio Server asks to save the workspace after the R session ends, and it always loads the workspace when starting a new session. Some organizations prefer to disable this behavior in order to discourage users from accumulating too much ad-hoc state. To do so, set the following:

*%PROGRAMDATA%\RStudio\rstudio-prefs.json*
```json
{
    "save_workspace": "never",
    "load_workspace": false
}
```

### Reference

A full list of preferences and their possible values can be found in the [RStudio Workbench Administration Guide](https://docs.rstudio.com/ide/server-pro/session-user-settings.html). Ensure that you reference the version of the guide that matches your version of RStudio Desktop Pro, as options can change between versions.

